// Copies the self-hosted font files from Fontsource and writes assets/css/fonts.css.
// Google Fonts is avoided on purpose: it is unreachable from mainland China (a focus market).
import { copyFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const nm = join(here, '..', 'node_modules', '@fontsource');
const pub = join(here, '..', '..', 'public');
const out = join(pub, 'assets', 'fonts');
mkdirSync(out, { recursive: true });

// unicode-range values mirror Fontsource's own subsets.
const RANGES = {
  latin: 'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  arabic: 'U+0600-06FF,U+0750-077F,U+0870-088E,U+0890-0891,U+0897-08E1,U+08E3-08FF,U+200C-200E,U+2010-2011,U+204F,U+2E41,U+FB50-FDFF,U+FE70-FE74,U+FE76-FEFC,U+102E0-102FB,U+10E60-10E7E,U+10EC2-10EC4,U+10EFC-10EFF,U+1EE00-1EEFF',
};
const FONTS = [
  // [package, family, subset, weights]
  ['lexend', 'Lexend', 'latin', [400, 600, 700]],
  ['sora', 'Sora', 'latin', [400, 600]],
  ['space-mono', 'Space Mono', 'latin', [400, 700]],
  ['noto-kufi-arabic', 'Noto Kufi Arabic', 'arabic', [500, 700]],
  ['ibm-plex-sans-arabic', 'IBM Plex Sans Arabic', 'arabic', [400, 600]],
];
let css = '/* GENERATED by dev/tools/fonts.mjs — self-hosted fonts (OFL-1.1, via Fontsource). */\n';
for (const [pkg, family, subset, weights] of FONTS) {
  for (const w of weights) {
    const file = `${pkg}-${subset}-${w}-normal.woff2`;
    copyFileSync(join(nm, pkg, 'files', file), join(out, file));
    css += `@font-face{font-family:"${family}";font-style:normal;font-weight:${w};font-display:swap;src:url(/assets/fonts/${file}) format("woff2");unicode-range:${RANGES[subset]}}\n`;
  }
}
writeFileSync(join(pub, 'assets', 'css', 'fonts.css'), css);
console.log('fonts written');
