// Generates geographic assets from world-atlas (Natural Earth, public domain):
//  1) public/assets/js/geo/globe-data.js — dot positions for the Markets globe (land-110m sampled on rings),
//     each tagged with a country code when it falls in Nigeria or a market country.
//  2) The inline Nigeria map SVG, injected into public/index.html between <!-- GEO:NIGERIA --> markers,
//     plus dev/out/geo/hubs.json with hub positions (percent of the map box) for the HTML labels.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { feature } from 'topojson-client';

const here = dirname(fileURLToPath(import.meta.url));
const nm = join(here, '..', 'node_modules', 'world-atlas');
const PUB = join(here, '..', '..', 'public');
const OUTD = join(here, '..', 'out', 'geo');
mkdirSync(OUTD, { recursive: true });
const load = f => JSON.parse(readFileSync(join(nm, f), 'utf8'));

// ---------- point in polygon (lon/lat) ----------
const inRing = (x, y, ring) => { let c = false; for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
  const [xi, yi] = ring[i], [xj, yj] = ring[j]; if ((yi > y) !== (yj > y) && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) c = !c; } return c; };
const polys = g => g.type === 'Polygon' ? [g.coordinates] : g.type === 'MultiPolygon' ? g.coordinates : [];
const inGeom = (lon, lat, g) => polys(g).some(p => inRing(lon, lat, p[0]) && !p.slice(1).some(h => inRing(lon, lat, h)));

// ---------- 1) globe dots ----------
const land = feature(load('land-110m.json'), load('land-110m.json').objects.land);
const c110 = load('countries-110m.json'); const countries = feature(c110, c110.objects.countries).features;
// country code -> world-atlas numeric id
export const TAGGED = { NG: '566', SA: '682', AE: '784', QA: '634', LB: '422', SY: '760', JP: '392', KR: '410', CN: '156' };
const tagList = Object.keys(TAGGED);
const tagGeoms = tagList.map(k => countries.find(f => f.id === TAGGED[k]).geometry);
const landGeoms = land.features.map(f => f.geometry);
const STEP = 2.4, dots = [];
for (let lat = -84; lat <= 84.001; lat += STEP) {
  const n = Math.max(8, Math.round(150 * Math.cos(lat * Math.PI / 180)));
  for (let i = 0; i < n; i++) {
    const lon = -180 + (i + 0.5) * 360 / n;
    if (!landGeoms.some(g => inGeom(lon, lat, g))) continue;
    const t = tagGeoms.findIndex(g => inGeom(lon, lat, g));
    dots.push([Math.round(lat * 10), Math.round(lon * 10), t + 1]);
  }
}
const buf = Buffer.alloc(dots.length * 5);
dots.forEach(([la, lo, t], k) => { buf.writeInt16LE(la, k * 5); buf.writeInt16LE(lo, k * 5 + 2); buf.writeUInt8(t, k * 5 + 4); });
mkdirSync(join(PUB, 'assets', 'js', 'geo'), { recursive: true });
writeFileSync(join(PUB, 'assets', 'js', 'geo', 'globe-data.js'),
  `// GENERATED by dev/tools/geo.mjs from world-atlas land-110m / countries-110m (Natural Earth, public domain).\n` +
  `// ${dots.length} land dots; each record = int16 lat*10, int16 lon*10, uint8 tag (0 = none, else 1-based index into TAGS).\n` +
  `export const TAGS = ${JSON.stringify(tagList)};\nexport const DOTS = "${buf.toString('base64')}";\n`);
console.log('globe dots', dots.length, 'tagged', dots.filter(d => d[2]).length);

// ---------- 2) Nigeria map ----------
const c50 = load('countries-50m.json'); const c50f = feature(c50, c50.objects.countries).features;
const FRAME = { lon0: 1.2, lon1: 16.2, lat0: 2.6, lat1: 15.0 };
const K = Math.cos(9.1 * Math.PI / 180);
const VW = 1000, SC = VW / ((FRAME.lon1 - FRAME.lon0) * K), VH = Math.round((FRAME.lat1 - FRAME.lat0) * SC);
const P = ([lon, lat]) => [(lon - FRAME.lon0) * K * SC, (FRAME.lat1 - lat) * SC];
// Douglas–Peucker simplification (projected units)
function dp(pts, tol) { if (pts.length < 3) return pts; let md = 0, idx = 0; const [a, b] = [pts[0], pts.at(-1)];
  const dx = b[0] - a[0], dy = b[1] - a[1], L = Math.hypot(dx, dy) || 1;
  for (let i = 1; i < pts.length - 1; i++) { const d = Math.abs(dy * pts[i][0] - dx * pts[i][1] + b[0] * a[1] - b[1] * a[0]) / L; if (d > md) { md = d; idx = i; } }
  return md > tol ? [...dp(pts.slice(0, idx + 1), tol).slice(0, -1), ...dp(pts.slice(idx), tol)] : [a, b]; }
// Sutherland–Hodgman clip to the frame (projected box)
function clip(ring) { const edges = [[p => p[0] >= -2, (a, b) => { const t = (-2 - a[0]) / (b[0] - a[0]); return [-2, a[1] + t * (b[1] - a[1])]; }],
  [p => p[0] <= VW + 2, (a, b) => { const t = (VW + 2 - a[0]) / (b[0] - a[0]); return [VW + 2, a[1] + t * (b[1] - a[1])]; }],
  [p => p[1] >= -2, (a, b) => { const t = (-2 - a[1]) / (b[1] - a[1]); return [a[0] + t * (b[0] - a[0]), -2]; }],
  [p => p[1] <= VH + 2, (a, b) => { const t = (VH + 2 - a[1]) / (b[1] - a[1]); return [a[0] + t * (b[0] - a[0]), VH + 2]; }]];
  let out = ring; for (const [inside, cut] of edges) { const inp = out; out = []; for (let i = 0; i < inp.length; i++) { const cur = inp[i], prev = inp[(i + inp.length - 1) % inp.length];
    if (inside(cur)) { if (!inside(prev)) out.push(cut(prev, cur)); out.push(cur); } else if (inside(prev)) out.push(cut(prev, cur)); } if (!out.length) break; } return out; }
const f1 = n => Math.round(n * 10) / 10;
// closed rings start and end on the same point, so simplify the two halves separately
const dpRing = (pts, tol) => { const m = pts.length >> 1; return [...dp(pts.slice(0, m + 1), tol).slice(0, -1), ...dp(pts.slice(m), tol)]; };
const pathOf = geom => polys(geom).map(p => p.map(r => clip(dpRing(r.map(P), 0.9))).filter(r => r.length > 2)
  .map(r => 'M' + r.map(q => `${f1(q[0])} ${f1(q[1])}`).join('L') + 'Z').join('')).join('');
const NEIGH = ['204', '562', '148', '120', '768', '288', '854', '140', '226']; // Benin, Niger, Chad, Cameroon, Togo, Ghana, Burkina Faso, CAR, Eq. Guinea
const ng = c50f.find(f => f.id === '566');
const neigh = NEIGH.map(id => c50f.find(f => f.id === id)).filter(Boolean).map(f => pathOf(f.geometry)).filter(Boolean);
const HUBS = { kano: [8.52, 12.0], lagos: [3.37, 6.45] }; // Port Harcourt removed at the client's request
const H = Object.fromEntries(Object.entries(HUBS).map(([k, v]) => [k, P(v).map(f1)]));
// Inland route: a gentle arc from Kano to the port, bent sideways (not road-shaped on purpose).
const arc = (a, b, bend) => { const mx = (a[0] + b[0]) / 2, my = (a[1] + b[1]) / 2, dx = b[0] - a[0], dy = b[1] - a[1];
  return `M${a[0]} ${a[1]}Q${f1(mx - dy * bend)} ${f1(my + dx * bend)} ${b[0]} ${b[1]}`; };
// sea legs end above the 'to export markets' label
const seaL = P([2.5, 4.1]).map(f1);
const kanoR = f1(1.8 * SC * 0.5 * (1 + K) / 2 * 2) / 2; // ~0.9° radius sourcing zone
const svg = `<svg class="ngmap-svg" viewBox="0 0 ${VW} ${VH}" aria-hidden="true" focusable="false">
<rect class="ng-sea" width="${VW}" height="${VH}"/>
<g class="ng-neigh">${neigh.map(d => `<path d="${d}"/>`).join('')}</g>
<path class="ng-land" d="${pathOf(ng.geometry)}"/>
<path class="ng-outline" d="${pathOf(ng.geometry)}"/>
<circle class="ng-zone" cx="${H.kano[0]}" cy="${H.kano[1]}" r="${kanoR}"/>
<path class="ng-route" id="ngRouteLagos" d="${arc(H.kano, H.lagos, 0.12)}"/>
<path class="ng-sea-route" id="ngSeaLagos" d="${arc(H.lagos, seaL, 0.1)}"/>
</svg>`;
writeFileSync(join(OUTD, 'nigeria.svg'), svg);
const pct = Object.fromEntries(Object.entries(H).map(([k, [x, y]]) => [k, { x: f1(x / VW * 100) + '%', y: f1(y / VH * 100) + '%' }]));
pct.seaLagos = { x: f1(seaL[0] / VW * 100) + '%', y: f1(seaL[1] / VH * 100) + '%' };
writeFileSync(join(OUTD, 'hubs.json'), JSON.stringify({ viewBox: [VW, VH], hubs: pct }, null, 1));
const idx = join(PUB, 'index.html');
if (existsSync(idx)) {
  const html = readFileSync(idx, 'utf8');
  const next = html.replace(/<!-- GEO:NIGERIA -->[\s\S]*?<!-- \/GEO:NIGERIA -->/, `<!-- GEO:NIGERIA -->${svg}<!-- /GEO:NIGERIA -->`);
  if (next !== html) { writeFileSync(idx, next); console.log('injected Nigeria map into index.html'); }
}
console.log('nigeria svg', svg.length, 'bytes; viewBox', VW, VH, JSON.stringify(pct));
