// 1) Traces TerraTrade's own pictograms (from the company-profile PDF) into an SVG sprite:
//    public/assets/img/icons.svg  — <symbol id="i-…"> using fill="currentColor" so CSS controls colour.
// 2) Renders favicons / app icons from public/assets/img/brand/mark.svg.
import Jimp from 'jimp';
import potrace from 'potrace';
import { chromium } from 'playwright';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const SRC = join(here, '..', 'src-assets');
const PUB = join(here, '..', '..', 'public');
const TMP = join(here, '..', 'out', 'icons');
mkdirSync(TMP, { recursive: true });

// [id, source, which pixels form the glyph: 'light' (white glyph on a green tile) or 'dark' (green glyph)]
const ICONS = [
  ['cow', 'p2_x22.png', 'light'], ['wheat', 'p2_x23.png', 'light'],
  ['rocket', 'i_p3_x33.png', 'light'], ['eye', 'i_p3_x34.png', 'light'], ['ship', 'i_p7_x78.png', 'light'],
  ['partnership', 'p8_x98.png', 'dark'], ['insight', 'p8_x99.png', 'dark'], ['farmer', 'p8_x100.png', 'dark'],
];
const N = 128, S = 4;
async function glyph(file, mode) {
  const img = await Jimp.read(join(SRC, file));
  img.contain(N, N);
  const m = new Jimp(N, N, 0xffffffff);
  img.scan(0, 0, N, N, (x, y, i) => {
    const d = img.bitmap.data, a = d[i + 3], lum = (d[i] + d[i + 1] + d[i + 2]) / 3;
    const on = mode === 'light' ? a > 128 && lum > 200 : a > 128 && lum < 140;
    if (on) m.setPixelColor(0x000000ff, x, y);
  });
  // White-on-tile icons: drop glyph pixels connected to the border or inside a small margin
  // (the PDF's white page corners around the rounded tiles). Outline icons legitimately touch the border.
  const on = (x, y) => m.bitmap.data[(y * N + x) * 4] === 0;
  const stack = [];
  if (mode === 'light') for (let k = 0; k < N; k++) for (let e = 0; e < 5; e++) stack.push([k, e], [k, N - 1 - e], [e, k], [N - 1 - e, k]);
  while (stack.length) {
    const [x, y] = stack.pop();
    if (x < 0 || y < 0 || x >= N || y >= N || !on(x, y)) continue;
    // stop the flood at the margin so it only strips the corner debris, never the glyph itself
    if (Math.min(x, y, N - 1 - x, N - 1 - y) > 10) continue;
    m.setPixelColor(0xffffffff, x, y);
    stack.push([x + 1, y], [x - 1, y], [x, y + 1], [x, y - 1]);
  }
  const f = join(TMP, file);
  await m.resize(N * S, N * S, Jimp.RESIZE_BILINEAR).blur(3).threshold({ max: 128 }).writeAsync(f);
  return new Promise((res, rej) => {
    const p = new potrace.Potrace();
    p.setParameters({ turdSize: 40, optTolerance: 0.8, threshold: 128, blackOnWhite: true });
    p.loadImage(f, e => e ? rej(e) : res(p.getPathTag().match(/ d="([^"]+)"/)[1]));
  });
}
const shrink = d => d.replace(/-?\d+(\.\d+)?/g, v => Math.round(+v / S).toString()).replace(/\s*,\s*/g, ' ').replace(/\s+/g, ' ');

let sprite = '<svg xmlns="http://www.w3.org/2000/svg" style="display:none">\n<!-- GENERATED by dev/tools/icons.mjs from TerraTrade\'s company-profile pictograms -->\n';
for (const [id, file, mode] of ICONS) {
  const d = shrink(await glyph(file, mode));
  sprite += `<symbol id="i-${id}" viewBox="0 0 ${N} ${N}"><path fill="currentColor" fill-rule="evenodd" d="${d}"/></symbol>\n`;
}
sprite += '</svg>\n';
writeFileSync(join(PUB, 'assets', 'img', 'icons.svg'), sprite);
console.log('sprite', sprite.length, 'bytes');

// ---- favicons ----
const mark = readFileSync(join(PUB, 'assets', 'img', 'brand', 'mark.svg'), 'utf8');
writeFileSync(join(PUB, 'favicon.svg'), mark);
const browser = await chromium.launch();
const page = await browser.newPage();
async function render(size, pad, bg) {
  await page.setViewportSize({ width: size, height: size });
  await page.setContent(`<body style="margin:0;background:${bg || 'transparent'};display:grid;place-items:center;height:${size}px">
    ${mark.replace('<svg ', `<svg width="${size - 2 * pad}" height="${size - 2 * pad}" `)}</body>`);
  return page.screenshot({ omitBackground: !bg });
}
writeFileSync(join(PUB, 'apple-touch-icon.png'), await render(180, 14, '#E9FFE5'));
writeFileSync(join(PUB, 'assets', 'img', 'brand', 'icon-192.png'), await render(192, 0));
writeFileSync(join(PUB, 'assets', 'img', 'brand', 'icon-512.png'), await render(512, 0));
writeFileSync(join(PUB, 'assets', 'img', 'brand', 'icon-maskable-512.png'), await render(512, 72, '#21401C'));
// favicon.ico with PNG payloads (valid since Vista; all current browsers)
const pngs = [];
for (const s of [16, 32, 48]) pngs.push([s, await render(s, 0)]);
await browser.close();
const head = Buffer.alloc(6 + 16 * pngs.length); head.writeUInt16LE(0, 0); head.writeUInt16LE(1, 2); head.writeUInt16LE(pngs.length, 4);
let off = head.length;
pngs.forEach(([s, buf], k) => { const o = 6 + 16 * k; head.writeUInt8(s, o); head.writeUInt8(s, o + 1); head.writeUInt16LE(1, o + 4); head.writeUInt16LE(32, o + 6); head.writeUInt32LE(buf.length, o + 8); head.writeUInt32LE(off, o + 12); off += buf.length; });
writeFileSync(join(PUB, 'favicon.ico'), Buffer.concat([head, ...pngs.map(p => p[1])]));
console.log('favicons written');
