// Generates the Arabic pages from the English source pages + public/assets/js/i18n/ar.js.
//   public/index.html          → public/ar/index.html
//   public/thanks/index.html   → public/ar/thanks/index.html
//   public/privacy/index.html  → public/ar/privacy/index.html
// A real /ar/ URL (instead of a JS-only switch) gives Arabic search indexing, hreflang, Arabic
// WhatsApp/social previews, no flash of English, and a page that works without JavaScript.
// Fails (exit 1) listing any key that is missing from ar.js.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { parseHTML } from 'linkedom';

const here = dirname(fileURLToPath(import.meta.url));
const PUB = join(here, '..', '..', 'public');
import { SITE } from '../site.mjs';
const AR = (await import(pathToFileURL(join(PUB, 'assets', 'js', 'i18n', 'ar.js')).href + '?t=' + Date.now())).default;
const PAGES = [['index.html', 'ar/index.html', '/', '/ar/'], ['thanks/index.html', 'ar/thanks/index.html', '/thanks/', '/ar/thanks/'],
  ['privacy/index.html', 'ar/privacy/index.html', '/privacy/', '/ar/privacy/'], ['404.html', 'ar/404.html', '/404.html', '/ar/404.html']];

const missing = new Set();
const get = k => { if (!(k in AR)) { missing.add(k); return null; } return AR[k]; };

for (const [src, dst, enPath, arPath] of PAGES) {
  const { document } = parseHTML(readFileSync(join(PUB, src), 'utf8'));
  const html = document.documentElement;
  html.setAttribute('lang', 'ar'); html.setAttribute('dir', 'rtl');
  for (const el of document.querySelectorAll('[data-i18n]')) {
    const v = get(el.getAttribute('data-i18n')); if (v == null) continue;
    if (el.children.length) throw new Error(`data-i18n on an element with children: <${el.tagName.toLowerCase()} data-i18n="${el.getAttribute('data-i18n')}">`);
    el.textContent = v;
  }
  for (const el of document.querySelectorAll('[data-i18n-html]')) { const v = get(el.getAttribute('data-i18n-html')); if (v != null) el.innerHTML = v; }
  for (const el of document.querySelectorAll('[data-i18n-attr]')) {
    for (const pair of el.getAttribute('data-i18n-attr').split(';')) { const [attr, key] = pair.split('='); const v = get(key); if (v != null) el.setAttribute(attr, v); }
  }
  for (const el of document.querySelectorAll('[data-i18n-list]')) {
    const v = get(el.getAttribute('data-i18n-list')); if (v == null) continue;
    el.setAttribute('data-words', JSON.stringify(v));
    const first = el.querySelector('.mword'); if (first) first.textContent = v[0];
  }
  // head: canonical / og for the Arabic URL, Arabic fonts preloaded instead of Latin ones
  document.querySelector('link[rel="canonical"]')?.setAttribute('href', SITE + arPath);
  document.querySelector('meta[property="og:url"]')?.setAttribute('content', SITE + arPath);
  const ogLoc = document.querySelector('meta[property="og:locale"]'), enLoc = ogLoc?.getAttribute('content') || 'en_GB';
  ogLoc?.setAttribute('content', 'ar_AR');
  document.querySelector('meta[property="og:locale:alternate"]')?.setAttribute('content', enLoc);
  // same cache-busting version as the English og:image (bump both when the images are regenerated)
  const ogImg = document.querySelector('meta[property="og:image"]'), ver = (ogImg?.getAttribute('content') || '').split('?')[1];
  ogImg?.setAttribute('content', SITE + '/assets/img/og-ar.jpg' + (ver ? '?' + ver : ''));
  const pre = [...document.querySelectorAll('link[rel="preload"][as="font"]')];
  if (pre[0]) pre[0].setAttribute('href', '/assets/fonts/noto-kufi-arabic-arabic-700-normal.woff2');
  if (pre[1]) pre[1].setAttribute('href', '/assets/fonts/ibm-plex-sans-arabic-arabic-400-normal.woff2');
  // the Arabic dictionary is imported by main.js before anything runs: fetch it in parallel with the module graph
  const mp = document.querySelector('link[rel="modulepreload"]');
  if (mp) { const l = document.createElement('link'); l.setAttribute('rel', 'modulepreload'); l.setAttribute('href', '/assets/js/i18n/ar.js'); mp.after(l); }
  let out = document.toString()
    // linkedom lowercases SVG filter element names; restore their canonical camelCase
    .replace(/<(\/?)fe(turbulence|displacementmap|colormatrix|gaussianblur)\b/g, (_, sl, n) => `<${sl}fe${{ turbulence: 'Turbulence', displacementmap: 'DisplacementMap', colormatrix: 'ColorMatrix', gaussianblur: 'GaussianBlur' }[n]}`);
  if (!/^<!doctype/i.test(out)) out = '<!doctype html>\n' + out;
  out = out.replace(/^<!doctype html>/i, '<!doctype html>\n<!-- GENERATED by dev/tools/render-ar.mjs from /' + src + ' + assets/js/i18n/ar.js. Do not edit by hand. -->');
  mkdirSync(join(PUB, dirname(dst)), { recursive: true });
  writeFileSync(join(PUB, dst), out + (out.endsWith('\n') ? '' : '\n'));
  console.log('wrote', dst);
}
if (missing.size) { console.error('Missing Arabic keys:\n  ' + [...missing].join('\n  ')); process.exit(1); }
